### ISSUE TITLE
In je CSS gebruik je te algemene selectors

### ISSUE THREAD

**Issue by JeroenHeemskerk** [Corby7/educom-webshop-basis#14]
In de code hieronder 
https://github.com/Corby7/educom-webshop-basis/blob/ddfc5322e3ea460087d86dd11b1215b90c0eb778/style.css#L36-L39
Verander je ALLE `<a>` tags om wit te worden, terwijl je alleen de a-tags die in het menu staan wilt aanpassen. Gebruik dan als selector iets als 
```CSS
nav > ul li > a {  /* een a tag die een child is van een li tag die staat binnen een ul tag dat een child is van de nav tag */
     color: white; 
     text-decoration: none; 
 } 
```
